### ISSUE TITLE
Does OpenTimestamps.verify() check if all the hashes in the merkle tree are correct?

### ISSUE THREAD

**Issue by etschelp** [opentimestamps/java-opentimestamps#14]
I hope you can help me understand this. I looked at the implementation of OpenTimestamps.verify() and I do not see that there is a check to verify if the local file hash really commits to the merkle root. I see two steps: first the hashes of the original file and the ots file are compared, second there is a check to see if the attestations saved with the ots really exist in a blockchain. But what I'm missing is a check that validates the path through the merkle tree from the file hash up to the root. Wouldn't this allow me to simply copy the attestation over to any other file and run verify() successfully as long as the two hashes check out?

**Comment by RCasatta** [comment]
That would be really, really bad.

When you say "there is a check to see if the attestations saved with the ots really exist in a blockchain" that implicity mean the merkle root to check against the blockchain has been calculated starting from the hash of the file. If you search for the bitcoin block merkle root in the binary receipt you would not find it, thus the only way to have it is to calculate it.

Please try to change a single byte in the path operations of a valid receipt and see if it is still verifies.
Or try to put the hash of the incomplete.txt file inside the hello-world.txt.ots (with an hex editor search for the hello-world.txt hash in the receipt and fill it with the incomplete.txt one). Than rename incomplete.txt to hello-world.txt.ots. Does this verify?

**Comment by etschelp** [comment]
Maybe this makes what I mean a bit clearer:

```
    @Test(expected = Exception.class)
    public void verify2() throws Exception {
        DetachedTimestampFile helloOts = DetachedTimestampFile.deserialize(helloworldOts);
        DetachedTimestampFile differentOts = DetachedTimestampFile.deserialize(differentBlockchainOts);

        helloOts.getTimestamp().attestations = differentOts.getTimestamp().attestations;
        helloOts.getTimestamp().ops = differentOts.getTimestamp().ops;

        DetachedTimestampFile detached = DetachedTimestampFile.from(Hash.from(helloworld, OpSHA256._TAG));
        OpenTimestamps.verify(helloOts, detached); // returns the timestamp of the second file
    }
```
Modifying the files wont work of course, but as the serialised file contains two parts: the hash of the original file and the attestations, it is possible to switch one valid attestation with another valid attestation and the verify() method will still succeed as both the hashes and the attestations are valid. Would there be a check that applies all the operations of the attestations again it would be evident that the file hash does not commit to the merkle root. Or am I completely wrong here?

**Comment by RCasatta** [comment]
I understand.
Well, what you are doing is playing with the low level API of the library and that is something that could happen. The reason why this happen is because the merkle root of the helloOts isn't recalculated every time you edit the ops but during the deserialization.
We could fix the behaviour by serializing and deserializing the timestamps objects at the beginning of the  OpenTimestamps.verify but I am not sure is something to fix, maybe just a better documentation of the function.

**Comment by etschelp** [comment]
OK I see. If this happens during deserialisation its alright. But then shouldn't adding the following line "fix" the test?

```
helloOts = DetachedTimestampFile.deserialize(helloOts.serialize());
```
The issue that I see is that if you have to store your raw and ots files in a potentially untrusted environment then someone could do exactly what I did, meaning change the original file switch the hash in the ots but leave the original attestation. and everything will still check out.

**Comment by RCasatta** [comment]
Yes, this test will pass

```
    @Test(expected = Exception.class)
    public void verify2() throws Exception {
        DetachedTimestampFile helloOts = DetachedTimestampFile.deserialize(helloworldOts);
        DetachedTimestampFile differentOts = DetachedTimestampFile.deserialize(differentBlockchainOts);

        helloOts.getTimestamp().ops = differentOts.getTimestamp().ops;

        DetachedTimestampFile detached = DetachedTimestampFile.from(Hash.from(helloworld, OpSHA256._TAG));
        helloOts = DetachedTimestampFile.deserialize(helloOts.serialize());

        System.out.println(OpenTimestamps.verify(helloOts, detached).toString()); // returns the timestamp of the second file
    }
```

**Comment by etschelp** [comment]
You are right this works. Then everything is fine. There is no need to do this check during verify() again, if you can not trust your runtime environment then you have bigger issues anyway. The one thing I would propose though is adding this test to your code base.

**Comment by RCasatta** [comment]
sure thing! I'll merge your request
