### ISSUE TITLE
Bitcoin verification failed: JSONObject["merkleroot"] not found

### ISSUE THREAD

**Issue by yurikilian** [opentimestamps/java-opentimestamps#17]
Hi,

This exception occurs when opentimestamps tries get info at https://btc-bitcore1.trezor.io/api. Looking into the response it gaves me HTTP 200 with: Blockbook - blockchain indexer for TREZOR wallet https://trezor.io/. Do not use for any other purpose.

Is this response returning because the block wasn`t found?

Assuming that, should we ignore this error like javascript lib or exclude this url from code? 

Thank you.

**Comment by RCasatta** [comment]
They probably switched to another API, the best thing one can do is using a local bitcoin node, in this way opentimestamps query the local node about blockchain information.

In the case the user haven't a local node, the lib try to ask different blockexplorer for blockchain information so in some cases a single explorer failing is not a problem (and you can ignore the exception)

**Comment by yurikilian** [comment]
Can it be merged?

**Comment by RCasatta** [comment]
Could you please fix the indentation?

**Comment by yurikilian** [comment]
Fixed.

**Comment by RCasatta** [comment]
merged
