### ISSUE TITLE
Archive on Maven Central is missing com.eternitywall.ots.VerifyResult

### ISSUE THREAD

**Issue by domseichter** [opentimestamps/java-opentimestamps#19]
Hi,

We integrate opentimestamps API using maven.

The version 1.15 of java-opentimestamps we get from maven central does not include several classes that are included in the sources on GitHub.

E.g. com.eternitywall.ots.VerifyResult is missing in the package on Maven central.

Link to Maven Central: https://search.maven.org/artifact/com.eternitywall/java-opentimestamps/1.15/jar

Is there a new release planned which will fix the archive on Maven Central?

**Comment by RCasatta** [comment]
Maven packages refer to the version tagged with the same number. So you have to checkout tag 1.15 to match what you find in maven. 
It's some time we didn't make a release, we should do one but it's not planned

**Comment by RCasatta** [comment]
just released version 1.16 on maven (it probably takes a while to be available)

**Comment by domseichter** [comment]
Issue resolved, closing ticket. Thank you for the fast response
