### ISSUE TITLE
Small bug in OtsCli with option "upgrade"

### ISSUE THREAD

**Issue by f-lombardo** [opentimestamps/java-opentimestamps#2]
Hi guys,
I thing there's a small bug in OtsCli class, where I think the ! operator should be deleted:

`            case "upgrade":
            case "u":
                if (files.isEmpty()) {`

Do you like me proposing a pull request? Do you need a Unit test for this?

Ciao

Franco

**Comment by RCasatta** [comment]
Hi @f-lombardo ! A pull request would be wonderful :)
Also, any unit test are welcome
