### ISSUE TITLE
MVN Install

### ISSUE THREAD

**Issue by lilsegwit** [opentimestamps/java-opentimestamps#22]
It appears `mvn install` step is not completing 

tried master and 1.16

Some tests are not completing
```
Tests in error: 
  TestMultiInsight.testMulti:19 » JSON JSONObject["merkleroot"] not found.
  TestOpenTimestamps.verify:153 NullPointer
  TestOpenTimestamps.upgrade:175 NullPointer
```

**Comment by RCasatta** [comment]
both in master and in 1.16 those lines are commented out, are you sure to be synced?
