### ISSUE TITLE
How to obtain OTS file with Java Client?

### ISSUE THREAD

**Issue by simbro** [opentimestamps/java-opentimestamps#25]
When I stamp a file using the command line, an OTS file is generated which can be used to later verify the file that was stamped.  How do I obtain the same OTS file when stamping a file using the client in code.

When I use the Java client in my code, as per the example in the docs, i.e.:

```
File initialFile = new File("/path/to/file.txt");
 InputStream targetStream = new FileInputStream(initialFile);
			
DetachedTimestampFile detached = DetachedTimestampFile.from(targetStream);
Timestamp stampResult = OpenTimestamps.stamp(detached);
String infoResult = OpenTimestamps.info(detached);
System.out.println(infoResult);
```

I get the following result:

```
Submitting to remote calendar https://alice.btc.calendar.opentimestamps.org
Submitting to remote calendar https://bob.btc.calendar.opentimestamps.org
Submitting to remote calendar https://finney.calendar.eternitywall.com
File sha256 hash: c8345eb5382b2d3f61f738cd1aa176398f64690bf7a88b04e3db1383fd713891
Timestamp:
append cc1f508d717ff4748c3a052c5d337abc
sha256
 -> append 0f9971c50c02067e90092e213ff25efd
    sha256
    prepend 5beaaf32
    append a0c3d5ef5747a576
    verify PendingAttestation('https://alice.btc.calendar.opentimestamps.org')
 -> append 2b4a28bac22f659d8a65b92aeef9e613
    sha256
    prepend 5beaaf32
    append 50d325f65f54a228
    verify PendingAttestation('https://bob.btc.calendar.opentimestamps.org')
 -> append ed24daeef52e10cfbcd65dca5afde495
    sha256
    append 5c81a51327f8470d3c7c68ccfc5fe6d7
    sha256
    append 14459f5e435b378b5dcadaf0b9d89250ebfab712077478ac91eb466d6b88bb4f
    sha256
    prepend 5beaaf32
    append 8a1aae8558182afd
    verify PendingAttestation('https://finney.calendar.eternitywall.com')
```

How to obtain the OTS file as I would if I stamp a file using the command line?

**Comment by lvaccaro** [comment]
Hi, OTS file is only the serialization in bytes of the `detached` object. 
For this purpouse, use the `serialize()` function:
https://github.com/opentimestamps/java-opentimestamps/blob/18b9fab24e3083923657d0cb27866a0cda200281/src/main/java/com/eternitywall/ots/DetachedTimestampFile.java#L90
like the following:
https://github.com/opentimestamps/java-opentimestamps/blob/18b9fab24e3083923657d0cb27866a0cda200281/src/main/java/com/eternitywall/ots/OtsCli.java#L350

**Comment by simbro** [comment]
Excellent - that worked perfectly - thank you!
