### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by harrigan** [opentimestamps/java-opentimestamps#34]
I am using `java-opentimestamps` as a dependency in a larger application. The application uses `logback-classic`, so when I start the application I get:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/martin/.m2/repository/com/eternitywall/java-opentimestamps/1.17/java-opentimestamps-1.17.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/martin/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

Could `java-opentimestamps` depend on `slf4j-api` instead of `slf4j-simple` to leave the choice of logging framework to the end user?

Thank you for creating the project!

**Comment by andreatessaro** [comment]
i  resolved this issue by modifying dependencies in pom.xml
I addedd dependency to slf4j-api and added scope provided to both slf4j dependencies
See attachment..
[pom.zip](https://github.com/opentimestamps/java-opentimestamps/files/3387278/pom.zip)

**Comment by brunocvcunha** [comment]
This can be handled if #36 is merged.
Then you can use like this:

```
        <dependency>
            <groupId>com.eternitywall</groupId>
            <artifactId>java-opentimestamps</artifactId>
            <version>1.17</version>
            <exclusions>
               <exclusion>
                 <groupId>org.slf4j</groupId>
                 <artifactId>slf4j-simple</artifactId>
               </exclusion>
            </exclusions>
        </dependency>
```

**Comment by RCasatta** [comment]
#36 has been merged, this should not be an issue anymore. Feel free to reopen if it is still an issue
