### ISSUE TITLE
maven jar

### ISSUE THREAD

**Issue by smarouani** [opentimestamps/java-opentimestamps#43]
Hi,

Last jar java-opentimestamps available on https://mvnrepository.com/artifact/com.eternitywall/java-opentimestamps  was build in Feb 2019.
This jar doesn't contain last fixes. Should I build the project locally ? or new version is planned?
Thanks a lot!

Saoussen

**Comment by RCasatta** [comment]
just pushed version 1.18 to mvn, should be visible soon

**Comment by youssefgh** [comment]
@RCasatta Examples from readme no longer work because of outdated APIs (blockexplorer, bitpay...)
New release is needed since master is working fine

**Comment by petertodd** [comment]
Be good to replace those with blockstream.info!

**Comment by youssefgh** [comment]
@petertodd master already uses esplora ;)

**Comment by RCasatta** [comment]
just pushed version 1.19 to mvn, should be visible soon
