### ISSUE TITLE
Verify incomplete timestamps from code

### ISSUE THREAD

**Issue by GTP95** [opentimestamps/java-opentimestamps#46]
Hello everyone.
The example code provided in the readme shows how to verify a timestamp that has been upgraded to be independently verifiable but fails the verification if the file was stamped using only a remote calendar, while opentimestamps-client is able to verify files with incomplete timestamps. How can I verify an incomplete timestamp from code?
Thanks for your help

**Comment by GTP95** [comment]
By looking at the javadocs I found the verify​(DetachedTimestampFile ots, DetachedTimestampFile stamped) method, whose description is  "Compare and verify a detached timestamp", so this seems to be the right method to use. But why it takes as arguments two DetachedTimestampsFile? It is because it compares two timestamps? What if I only need to verify a single timestamp? Should I pass the same DetacedTimestampFile twice?
Thanks in advance to anyone who explains me this.

**Comment by BrunoMend** [comment]
Hi @GTP95 
I'm not sure if it is possible to check the stamped data without updating the OTS data in this Java client library. To be sure, I always call upgrade method before verify.
The function verify​(DetachedTimestampFile ots, DetachedTimestampFile stamped) receives the ots data and the original data. Here is a way to perform this operation (in Kotlin way):

```
fun verify(originalData: ByteArray, otsData: ByteArray) {
   val detachedFile: DetachedTimestampFile = DetachedTimestampFile.from(OpSHA256(), originalData)
   val detachedOts: DetachedTimestampFile = DetachedTimestampFile.deserialize(otsData)	
   OpenTimestamps.upgrade(detachedOts)
   OpenTimestamps.verify(detachedOts, detachedFile)
}
```

**Comment by GTP95** [comment]
Thank you @BrunoMend and sorry for replying so late to your comment, I tried your suggestion and then had to swich to other things and I only come back to this project in these days.
Calling the upgrade function before verifying seems the way to go, in fact I can verify my timestamps in that way. But unfortunately the code to verify wheter the ots data is complete or not doesn't seem to work, for it always returns that the ots data is incomplete, even if it is.  Here's the Java code I'm using to verify the timestamp onto the blockchain:
```Java
public String checkTimestampOnBlockchain(File zippedArchive) throws Exception {
        String tempDir = Main.getTempDir();
        String filePath = tempDir + File.separator + FilenameUtils.removeExtension(zippedArchive.getName());
        String otsFilePath = tempDir + File.separator + FilenameUtils.removeExtension(zippedArchive.getName()) + ".ots";

        new ZipFile(zippedArchive).extractAll(tempDir);

        byte[] file = Files.readAllBytes(Paths.get(filePath));
        byte[] fileOts = Files.readAllBytes(Paths.get(otsFilePath));

        DetachedTimestampFile detached = DetachedTimestampFile.from(new OpSHA256(), file);
        DetachedTimestampFile detachedOts = DetachedTimestampFile.deserialize(fileOts);

        OpenTimestamps.upgrade(detachedOts);


        if(!isOtsComplete(fileOts)) return languageResourceBundle.getString("pendingAttestation");

        String esito = "";



        HashMap<VerifyResult.Chains, VerifyResult> result = OpenTimestamps.verify(detachedOts, detached);

        if (result == null || result.isEmpty()) {
            esito = languageResourceBundle.getString("badAttestation");
        } else {
            for (Map.Entry<VerifyResult.Chains, VerifyResult> entry : result.entrySet()) {
                VerifyResult.Chains k = entry.getKey();
                VerifyResult v = entry.getValue();
                esito += languageResourceBundle.getString("success")+'\n' + k + languageResourceBundle.getString("attestsDataExistedAsOf") + new Date(v.timestamp * 1000) + "\n";
            }
        }


        return esito;
    }
```

And here's my Java translation of your Kotlin code to check if the timestamp is complete:
```Java
private boolean isOtsComplete(byte[] ots){
        Timestamp timestamp=DetachedTimestampFile.deserialize(ots).getTimestamp();
        for(Timestamp subStamp : timestamp.directlyVerified()){
            for(TimeAttestation subAttestation : subStamp.attestations){
                if(subAttestation.getClass() == PendingAttestation.class && !subStamp.isTimestampComplete()) return false;
            }
        }
        return true;
    }
```

If I run this code it fails the verification saying that the registration is still pending, while if i comment out the line `if(!isOtsComplete(fileOts)) return languageResourceBundle.getString("pendingAttestation");` from the method "checkTimestampOnBlockchain" the timestamp gets verified correctly. What Am I missing?

**Comment by BrunoMend** [comment]
Hi @GTP95 
It seems to me that you are passing the outdated fileOts to isOtsComplete. Try replacing this line with:
`if(!isOtsComplete(detachedOts.serialize())) return languageResourceBundle.getString("pendingAttestation");`

**Comment by GTP95** [comment]
You are right! I missed that I was still passing the non-upgraded version. I modified it and now it seems to work! I'll do more testing, but I think the issue is resolved now. Thank you very much!
